// THIS FILE IS AUTO GENERATED BY graphql-code-generator
// TEMPLATE: graphql-codegen-apollo-angular-template
// Do Pass Valid Configuration in "codegen.yml" file for Auto Generator

import { Injectable } from '@angular/core';
import { Query, Mutation } from 'apollo-angular';
import gql from 'graphql-tag';

export type Author = {
  id: number;
  firstName: string;
  lastName: string;
};

export type Post = {
  id: number;
  title: string;
  votes: number;
};

export type AllPostsQuery = {
  posts: Post[];
};

export type UpvotePostMutation = {
  upvotePost: Post;
};

export type UpvotePostVariables = {
  postId: number;
};

export type ExchangeRate = {
    currency: string;
    rate: string;
    name: string;
};


@Injectable({
  providedIn: 'root'
})
export class AllPostsGQL extends Query<AllPostsQuery, {}> {
  document = gql`
    query allPosts {
      posts {
        id
        title
        votes
        author {
          id
          firstName
          lastName
        }
      }
    }
  `;
}

@Injectable({
  providedIn: 'root'
})
export class UpvotePostGQL extends Mutation<UpvotePostMutation, UpvotePostVariables> {
  document = gql`
    mutation upvotePost($postId: Int!) {
      upvotePost(postId: $postId) {
        id
        votes
      }
    }
  `;
}


@Injectable({
    providedIn: 'root'
  })
  export class GetRatesGQL extends Query<ExchangeRate[]> {
    document = gql`
      {
        rates(currency: "USD") {
          currency
          rate
        }
      }
    `;
  }
